---
abstract: 'An HTTP server that can be killed by an application'
author:
  - 'Laurent Dami, C<< <dami at cpan.org> >>'
  - 'Laurent Dami <dami@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  LWP::UserAgent: 0
  Plack::Runner: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Server-PSGI-Mortal
no_index:
  directory:
    - inc
    - t
requires:
  HTTP::Server::PSGI: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
